OPENQASM 2.0;
include "qelib1.inc";
qreg anne[2];
qreg bob[1];
qreg clara[2];
creg received message[2];
h anne[0];
cx anne[0],anne[1];
barrier anne[0],anne[1],bob[0],clara[0],clara[1];
swap anne[0],bob[0];
swap anne[1],clara[0];
barrier anne[0],anne[1],bob[0],clara[0],clara[1];
z bob[0];
barrier anne[0],anne[1],bob[0],clara[0],clara[1];
swap bob[0],clara[1];
barrier anne[0],anne[1],bob[0],clara[0],clara[1];
cx clara[0],clara[1];
h clara[0];
barrier anne[0],anne[1],bob[0],clara[0],clara[1];
measure clara[0] -> received message[0];
measure clara[1] -> received message[1];
